apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: subscriber
  namespace: custom-metrics
spec:
  minReplicas: 1
  maxReplicas: 30
  metrics:
  - external:
      metric:
       name: pubsub.googleapis.com|subscription|num_undelivered_messages
       selector:
         matchLabels:
           metadata.system_labels.name: example-subscription
      target:
        type: AverageValue
        averageValue: 100
    type: External
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: subscriber
